import z from "zod";

export const HITLOutputSchema = z.object({
  response: z.string().describe("The response generated by the agent"),
});

export type HITLOutputType = z.infer<typeof HITLOutputSchema>;
